# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67fda8dbf2a2c4c5d5571abf21e192e68c37187ca53a1d1d840f8d4ad8ec52b58b9d07979c35ca3aa54c6e02445a255396bfbeed314da3759b726f69fff929af

test:
  secret_key_base: 12387c66d7f9f57dc92321cfd93f65da6a7dbf4652cd410e0667c3768a2813d208e9850c5c49302a33f5223bd26e56cabd1cea9b2afa174aa9f88b71dfc2e6a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
